#!/usr/bin/env node

/** -----------------------------------------------------------------------------------------------
 * it.js
 */
var log = console.log;

function It(parent) {
  function it(value, func) {
    if (typeof func === "function") {
      it.promise = it.promise.then(function () {
        log(value);
        var child = It(it);
        return Promise.resolve(func(child)).then(function(){
          return child.promise;
        });
      }).catch(function (error) {
        log("  \x1b[31m⦸ %s\x1b[0m", error && error.message || error);
      });
    }
    else {
      log(value ? "  \x1b[32m✔ %s\x1b[0m" : "  \x1b[31m✘ %s\x1b[0m", source());
    }
  }

  it.promise = Promise.resolve();

  it.delay = function (time, value) {
    return new Promise(function (resolve) {
      setTimeout(resolve, time, value);
    });
  }

  return it;
}

/** -----------------------------------------------------------------------------------------------
 * src.js
 */

var fs = require("fs");

function source() {
  var trace = _where_(2);
  var lines = getlines(trace.loc);
  var source = lines[trace.row];
  return source ? source.trim() : "< no topic >";
}

function _where_(deep) {
  var stack = Error().stack.split("\n"), ms;
  for (var i = 0, line; line = stack[i++];) {
    if (line.match(reWhere)) break;
  }
  if (i < stack.length && (ms = String(stack[i + deep]).match(reHere))) {
    return {
      loc: ms[1],
      row: ms[2] - 1
    };
  }
}
var reWhere = RegExp('\\b' + _where_.name + '\\b');
var reHere = /((?:https?:\/\/[\w.-]+(?::\d+)?|)[\w./@-]+(?:\?.*|)):(\d+):(\d+)/;

function getlines(path) {
  if (path in getlines) {
    path = getlines[path];
  }
  else {
    path = getlines[path] = get(path).split("\n");
  }
  return path;
}

function get(path) {
  return fs.readFileSync(path, "utf-8");
}

/** -----------------------------------------------------------------------------------------------
 * it
 */
var path = require("path");

var files = process.argv.slice(2);
if (files.length) {
  global.it = It(null);
  files.map(function (file) {
    file = path.resolve(file);
    file = path.relative(__dirname, file);
    if (/^[^./]/.test(file)) {
      file = "./" + file;
    }
    require(file);
  });
}
